eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: ribbon-service

# 负载均衡配置
  cloud:
    loadbalancer:
      enabled: false