#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: user-service

dubbo:
  application:
    #当前应用名称，用于注册中心计算应用间依赖关系，提供者与消费者应用名不能一样.
    name: dubbo-user-service-provider
  #注册协议和端口,-1标识默认值.
  protocol:
    name: dubbo
    port: -1
  #注册中心ID与地址。提供者与消费者注册 id 保证相同，且唯一即可，address 为注册中心IP地址。
  registry:
    id: zk-registry
    address: zookeeper://localhost:2181
  #配置中心ID与地址
  config-center:
    address: zookeeper://localhost:2181
  #元数据中心ID与地址
  metadata-report:
    address: zookeeper://localhost:2181